#!/bin/bash
set -e

VLN1=12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
VLN1_KEY=0000000000000000000000000000000000000000000000000000000000000001
VLN1_PORT=30333

bootnodes() {
	nodes=
	for node in "$@"; do
	case "$node" in
		vln) nodes="${nodes} --bootnodes /dns/blockchain.valiu.dev/tcp/$VLN1_PORT/p2p/$VLN1";;
	esac
	done
	echo $nodes
}

NAME=$(hostname)
FLAGS=

case "$NAME" in
	odin) FLAGS="--validator $(bootnodes vln)";;
	thor) FLAGS="--validator $(bootnodes vln)";;
	loki) FLAGS="--validator $(bootnodes vln)";;
	*) FLAGS="--rpc-external --ws-external --rpc-cors all --node-key $VLN1_KEY";;
esac

sed -i "s~CHAIN_NAME~$NAME~" /usr/lib/systemd/system/app.service
sed -i "s~EXTRA_FLAGS~$FLAGS~" /usr/lib/systemd/system/app.service
